language: python
python:
  - "3.6"

sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10

before_install:
  - cd "${TRAVIS_BUILD_DIR}"
  - if [ "$TRAVIS_OS_NAME" = "linux" ] then ./.travis/install-opencl-linux.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] then echo "OpenCL should be present on OS X"; fi
  - pip install -r requirements.txt

script:
  - ./run-tests.sh

after_success:
  - echo SUCCESS
